### ISSUE TITLE
Youtube Playlist handling Issues

### ISSUE THREAD

**Issue by gmedeadlystrike** [HyperCoder2975/simple-youtube-api#11]
`Youtube#getPlaylist()` is unable to find the ID in a url such as
https://www.youtube.com/watch?v=djV11Xbc914&list=RDQM7qP9bWY13rQ

`Youtube#getPlaylistByID()` when passing in a ID such as `PLMC9KNkIncKtsacKpgMb0CVq43W80FKvo`
the videos array is always empty

**Comment by appellation** [comment]
Actually, I'd like to amend my previous statement.

In the case that a URL of the format `?v=videoID&list=playlistID` is provided, which is the intended resource: the video or the playlist?  In our case, we assume the video is intended.  Typically that format of URL is pasted from a browser page, wherein the user is viewing a video that is part of a playlist; it is, in my opinion, more logical to assume that they intend to link the video itself rather than the whole playlist.

**Comment by gmedeadlystrike** [comment]
I would think if `Youtube#getPlaylist()` is being called its the playlist thats intended 

and if `Youtube#getVideo()` is being called its the video that's intended

**Comment by appellation** [comment]
My apologies, I was thinking of a different scenario.

**Comment by appellation** [comment]
fixed in fecd06eeebf16afb90d0e76bbcb40fb1fa79bbc5
