### ISSUE TITLE
parseUrl returns null for valid youtu.be links

### ISSUE THREAD

**Issue by gmedeadlystrike** [HyperCoder2975/simple-youtube-api#26]
https://youtu.be/kJQP7kiw5Fk is the link format given when clicking "Share" on youtube and from looking at the code, it looks like there was an intent to support it. 

Currently all youtu.be links that I have tested return null when parsed.

**Comment by appellation** [comment]
I haven't seen this at all in the latest master.  I updated our URL parsing tests to reflect this; you can confirm this on [Travis](https://travis-ci.org/HyperCoder2975/simple-youtube-api/builds/374484944).  Considering that URL parsing has not changed since v5, I would be surprised if it were broken in the latest release.

**Comment by gmedeadlystrike** [comment]
Ahh ok @appellation you are correct. It looks like it runs successful on master. I was on the npm branch which seems to be 2 major versions behind (3.0.1) vs (5.0.2).

Thanks.

**Comment by appellation** [comment]
v5 should be available on npm

**Comment by gmedeadlystrike** [comment]
I guess it is.. stupid npm - updated npm, and now im getting the latest version.
